export const SN_UTIL = 'util';
export const UTIL_SHIPMENT_METHODS_UPDATED = SN_UTIL + '/SHIPMENT_METHODS_UPDATED';
export const UTIL_COUNTRY_OPTIONS_UPDATED = SN_UTIL + '/COUNTRY_OPTIONS_UPDATED';
export const UTIL_STATE_OPTIONS_UPDATED = SN_UTIL + '/STATE_OPTIONS_UPDATED';