export const SN_UTIL = 'util';
export const UTIL_SHIPMENT_METHODS_UPDATED = SN_UTIL + '/SHIPMENT_METHODS_UPDATED';
export const UTIL_COUNTRIES_UPDATED = SN_UTIL + '/COUNTRIES_UPDATED';
export const UTIL_STATES_UPDATED = SN_UTIL + '/STATES_UPDATED';