import {
  api,
  client,
  getConfig,
  getNotificationEnumIds,
  getNotificationUserPrefTypeIds,
  getProductIdentificationPref,
  getUserFacilities,
  hasError,
  initialise,
  logout,
  removeClientRegistrationToken,
  resetConfig,
  setProductIdentificationPref,
  setUserLocale,
  storeClientRegistrationToken,
  subscribeTopic,
  unsubscribeTopic,
  updateInstanceUrl,
  updateToken, 
  getAvailableTimeZones, 
  setUserTimeZone
} from '@hotwax/oms-api'

export {
  api,
  client,
  getConfig,
  getNotificationEnumIds,
  getNotificationUserPrefTypeIds,
  getProductIdentificationPref,
  getUserFacilities,
  hasError,
  initialise,
  logout,
  removeClientRegistrationToken,
  resetConfig,
  setProductIdentificationPref,
  setUserLocale,
  storeClientRegistrationToken,
  subscribeTopic,
  unsubscribeTopic,
  updateInstanceUrl,
  updateToken,
  getAvailableTimeZones, 
  setUserTimeZone
}