import {
  api,
  client,
  getConfig,
  getProductIdentificationPref,
  hasError,
  getUserFacilities,
  getNotificationEnumIds,
  getNotificationUserPrefTypeIds,
  initialise,
  logout,
  resetConfig,
  removeClientRegistrationToken,
  setProductIdentificationPref,
  storeClientRegistrationToken,
  subscribeTopic,
  unsubscribeTopic,
  updateInstanceUrl,
  updateToken
} from '@hotwax/oms-api'

export {
  api,
  client,
  getConfig,
  getProductIdentificationPref,
  hasError,
  getUserFacilities,
  getNotificationEnumIds,
  getNotificationUserPrefTypeIds,
  initialise,
  logout,
  resetConfig,
  removeClientRegistrationToken,
  setProductIdentificationPref,
  storeClientRegistrationToken,
  subscribeTopic,
  unsubscribeTopic,
  updateInstanceUrl,
  updateToken
}