export default {
  'APP_ORDER_UPDATE': 'APP_ORDER_UPDATE',
  'APP_RF_CONFIG_UPDATE': 'APP_RF_CONFIG_UPDATE',
  'APP_PARTIAL_ORDER_REJECTION_CONFIG_UPDATE': 'APP_PARTIAL_ORDER_REJECTION_CONFIG_UPDATE',
}