export default {
    "APP_ORDERS_VIEW": "",
    "APP_CATALOG_VIEW": "",
    "APP_ORDER_DETAIL_VIEW": "",
    "APP_PRODUCT_DETAIL_VIEW": "",
    "APP_ORDER_UPDATE": "COMMON_ADMIN",
    "APP_RF_CONFIG_UPDATE": "COMMON_ADMIN"
} as any 