export const SN_PICKLIST = 'picklist'
export const PICKLIST_PICKERS_UPDATED = SN_PICKLIST + '/PICKERS_UPDATED'
export const PICKLIST_SELECTED_PICKERS_UPDATED = SN_PICKLIST + '/SELECTED_PICKERS_UPDATED'
