export const SN_ORDERS = 'orders'
export const ORDERS_CURRENT_UPDATED = SN_ORDERS + '/CURRENT_UPDATED'
export const OPEN_ORDERS_INITIAL = SN_ORDERS + '/ORDERS_INITIAL'
export const ORDERS_PACKED_INITIAL = SN_ORDERS + '/PACKED_INITIAL'
